version: '3'
services:

  nifi:
    image: apache/nifi:2.2.0
    container_name: nifi
    hostname: nifi
    volumes:
      - ./keystore.jks:/opt/certs/keystore.jks
      - ./truststore.jks:/opt/certs/truststore.jks
    ports:
      - "8443:8443"
    environment:
      - KEYSTORE_PATH=/opt/certs/keystore.jks
      - KEYSTORE_TYPE=JKS
      - KEYSTORE_PASSWORD=${KEYSTORE_PASSWORD}
      - TRUSTSTORE_PATH=/opt/certs/truststore.jks
      - TRUSTSTORE_PASSWORD=${TRUSTSTORE_PASSWORD}
      - TRUSTSTORE_TYPE=JKS
      - INITIAL_ADMIN_IDENTITY=${INITIAL_ADMIN_IDENTITY}
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    restart: unless-stopped