version: '3'
services:
  nifi:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nifi
    hostname: nifi
    ports:
      - "8443:8443"
    environment:
      - INITIAL_ADMIN_IDENTITY=${INITIAL_ADMIN_IDENTITY}
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    restart: unless-stopped
